server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 0
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/personalproject?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
    username: root
    password: mysql
  application:
    name: personalProject
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
    annotation-driven: true